version: "3.8"
services:
  fhir-server:
    image: "ghcr.io/dot-base/fhir-server:latest"
    environment:
      HAPI_DATASOURCE_URL: "jdbc:postgresql://fhir-postgres:5432/hapi_r4"
      HAPI_DATASOURCE_USERNAME: "${FHIR_DB_USER:-admin}"
      HAPI_DATASOURCE_PASSWORD: "${FHIR_DB_PASSWORD:-admin}"
      HAPI_AUTHENTICATION__INTERCEPTOR_ENABLED: "true"
      HAPI_SSO_REALM_URL: ${SSO_REALM_URL}""

    ports:
      - "8080:8080"
    networks:
      - backend
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  fhir-postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: "${FHIR_DB_USER:-admin}"
      POSTGRES_PASSWORD: "${FHIR_DB_PASSWORD:-admin}"
      POSTGRES_DB: "hapi_r4"
      
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - fhir-postgres-data:/var/lib/postgresql/data
    deploy:
      placement:
        max_replicas_per_node: 1

networks:
  backend:

volumes:
  fhir-postgres-data: